[build-system]
requires = [
  "setuptools-scm",
  "wheel",
  "setuptools",
  "setuptools >= 42",
  "setuptools_scm[toml] >= 3.5.0",
  "setuptools_scm_git_archive >= 1.1",
]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = true
line-length = 99

[tool.isort]
profile = "black"
# known_first_party = "foo"
line_length = 99
multi_line_output = 3

[tool.setuptools_scm]
local_scheme = "no-local-version"

[tool.moat]

[tool.flake8]
max-line-length = 99
ignore = ["F841","F401","E731","E502","E402","E127","E123","E203","E231","W503"]
exclude = ["moat/micro/_embed"]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py310,check

[testenv]
setenv = 
    PYTHONPATH = {env:PYTHONPATH}{:}{toxinidir}
deps = 
    trio
    pytest
commands = 
    python3 -mpytest tests/

[testenv:check]
commands = 
    pylint moat tests
    flake8p moat tests
    black --check moat tests
deps = 
    pytest
    pylint
    black
    flake8-pyproject
    flake8

"""

[tool.setuptools]
packages = ["moat.micro"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]

[tool.pylint.messages_control]
disable = "wrong-import-order,use-dict-literal,unspecified-encoding,ungrouped-imports,too-many-statements,too-many-return-statements,too-many-nested-blocks,too-many-locals,too-many-instance-attributes,too-many-branches,too-many-arguments,too-few-public-methods,superfluous-parens,no-else-return,no-else-continue,invalid-name,fixme"

[project]
classifiers = ["Development Status :: 4 - Beta","License :: OSI Approved","Framework :: AnyIO","Framework :: Trio","Framework :: AsyncIO","Programming Language :: Python :: 3","Intended Audience :: Developers"]
dynamic = ["version"]
keywords = ["MoaT"]
dependencies = [
  "anyio ~= 3.0",
  "msgpack",
  "serialpacker",
  "pyfuse3 >= 3.2",
  "moat-util ~= 0.33.1",
  "moat-main",
]
requires-python = ">=3.8"
name = "moat-micro"
authors = [{email = "matthias@urlichs.de",name = "Matthias Urlichs"}]
description = "REPLACE ME"
readme = "README.rst"

[project.license]
file = "LICENSE.txt"

[project.urls]
homepage = "https://m-o-a-t.org"
repository = "https://github.com/M-o-a-T/moat-micro"
